name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # <--- Updated to v3
      - name: Set up Python
        uses: actions/setup-python@v3 # <--- Updated to v3
        with:
          python-version: "3.x"
          node-version: "20" # <--- Added Node.js version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s tests -p '*_test.py'
